name: docguru
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.2
  flutter_dotenv: ^5.0.2
  shared_preferences:
  pinput: ^5.0.1
  file_picker: ^8.3.3
  dio: ^5.8.0+1
  flutter_spinkit:
  flutter_rating_bar: ^4.0.1
  video_player:
  animated_text_kit: ^4.2.3
  liquid_progress_indicator_v2: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/splash.mp4
    - assets/splash_logo.png
    - assets/p1.png
    - assets/p2.png
    - assets/p3.png
    - assets/p4.png

  fonts:
  - family: TimesNewRoman
    fonts:
      - asset: assets/fonts/times-new-roman.ttf
  - family: Rokkitt
    fonts:
      - asset: assets/fonts/Rokkitt-Regular.ttf
  - family: Quantico
    fonts:
      - asset: assets/fonts/Quantico-Regular.ttf