name: docguru
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_dotenv: ^5.0.2
  shared_preferences:
  pinput: ^5.0.1
  file_picker: ^8.3.3
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/.env

  fonts:
  - family: TimesNewRoman
    fonts:
      - asset: assets/fonts/times-new-roman.ttf
  - family: Rokkitt
    fonts:
      - asset: assets/fonts/Rokkitt-Regular.ttf
  - family: Quantico
    fonts:
      - asset: assets/fonts/Quantico-Regular.ttf